import math
import array

#Problem 2
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#                                           1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

arr = [2]

def evenNumber(n):
    if n%2 == 0:
        return True
    
def evenTerms():
    sum = 0
    firstTermOfFibonacci = 1
    secondTermOfFibonacci = 2
    
    while  sum < 4000000:
        sum = firstTermOfFibonacci + secondTermOfFibonacci
        if evenNumber(sum) :
            arr.append(sum)
        firstTermOfFibonacci = secondTermOfFibonacci
        secondTermOfFibonacci = sum

def sumOfEvenTerms():
    evenTerms()
    sum = 0
    for i in arr:
        sum = sum + i
    return sum

print("Sum of even terms which not exceed 4 000 000 is :", sumOfEvenTerms())


